# Generated by Django 6.0 on 2026-01-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_form_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_From_CEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ceo_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ceo_messages/')),
            ],
        ),
    ]
