# Generated by Django 6.0 on 2026-02-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_notices'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notices/'),
        ),
    ]
